// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIBYqKdLGDeKEdQ-ND2bNwqqremMTJqlM',
    appId: '1:467314466496:web:ff39ef95d97ddd64fe1725',
    messagingSenderId: '467314466496',
    projectId: 'tokio-2c7ce',
    authDomain: 'tokio-2c7ce.firebaseapp.com',
    storageBucket: 'tokio-2c7ce.appspot.com',
    measurementId: 'G-T99ND8R9DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkw-hKgM2kAgzwTUaBnVNxxRqCkWNbOz8',
    appId: '1:467314466496:android:f414ab12bd977ed3fe1725',
    messagingSenderId: '467314466496',
    projectId: 'tokio-2c7ce',
    storageBucket: 'tokio-2c7ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl0xpAKSxlDHHWvH0ZM8IHLdzofG1Ukns',
    appId: '1:467314466496:ios:df4c1f49ec578a19fe1725',
    messagingSenderId: '467314466496',
    projectId: 'tokio-2c7ce',
    storageBucket: 'tokio-2c7ce.appspot.com',
    iosClientId: '467314466496-iqhmrfr1h1irbu75ll2gl2jq302728ac.apps.googleusercontent.com',
    iosBundleId: 'com.example.tokio',
  );
}
